name: rtb

services:
  rtb-db:
    container_name: rtb-db-mongo
    image: mongo:7.0.12-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?mongo_root_username_missing}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?mongo_root_password_missing}
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
      - type: volume
        source: mongo-config
        target: /data/configdb

  rtb-api:
    build: ./rtb-api
    container_name: rtb-api
    environment:
      DB_URL: rtb-db
      DB_PASSWORD: ${DB_PASSWORD:?db_password_missing}
    ports:
      - 3000:3000
    depends_on:
      - rtb-db

  rtb-spa:
    build: ./rtb-spa
    container_name: rtb-spa
    ports:
      - 80:80
    depends_on:
      - rtb-api


volumes:
  mongo-data:
  mongo-config: