# local db for development
# run create-db-user.sh script with the db container running in order to add a db user that api uses

name: rtb-db

services:
  rtb-db_dev:
    container_name: rtb-db-mongo
    image: mongo:7.0.12-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?mongo_root_username_missing}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?mongo_root_password_missing}
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo-data
        target: /data/db
      - type: volume
        source: mongo-config
        target: /data/configdb

volumes:
  mongo-data:
  mongo-config: